export default interface Classes {
    container?: String|String[],
    containerDisabled?: String|String[],
    containerOpen?: String|String[],
    containerActive?: String|String[],
    label?: String|String[],
    search?: String|String[],
    placeholder?: String|String[],
    clear?: String|String[],
    clearCross?: String|String[],
    dropdown?: String|String[],
    dropdownHidden?: String|String[],
    options?: String|String[],
    option?: String|String[],
    optionSelected?: String|String[],
    optionNotShown?: String|String[],
    spacer?: String|String[],
}