export const defaultTheme = {
  container: 'h-auto relative mx-auto w-full flex items-center justify-end box-border cursor-pointer border border-gray-300 bg-white rounded text-base leading-snug outline-none',
  containerDisabled: 'h-auto relative mx-auto w-full flex items-center justify-end box-border cursor-default border border-gray-300 bg-gray-100 rounded text-base leading-snug outline-none',
  containerActive: 'h-auto relative mx-auto w-full flex items-center justify-end box-border cursor-pointer border border-gray-300 bg-white rounded text-base leading-snug outline-none rounded-b-none ring ring-opacity-70 ring-orange-400',
  label: 'flex items-center h-full absolute left-0 top-0 pointer-events-none bg-transparent leading-snug pl-3.5',
  search: 'w-full absolute inset-0 outline-none appearance-none box-border border-0 text-base font-sans bg-white rounded pl-3.5',
  placeholder: 'flex items-center h-full absolute left-0 top-0 pointer-events-none bg-transparent leading-snug pl-3.5 text-gray-400',
  clear: 'pr-3.5 relative z-10 opacity-40 transition duration-300 flex-shrink-0 flex-grow-0 flex hover:opacity-80',
  clearIcon: 'text-lg font-bold text-center pl-3',
  dropdown: 'max-h-60 absolute -left-px -right-px bottom-0 transform translate-y-full border border-gray-300 -mt-px overflow-hidden overflow-y-auto z-50 bg-white flex flex-col rounded-b',
  dropdownHidden: 'hidden',
  options: 'flex flex-col p-0 m-0 list-none',
  option: 'flex items-center justify-start box-border text-left cursor-pointer text-base leading-snug py-2 px-3 hover:text-gray-800 hover:bg-gray-100',
  optionSelected: 'flex items-center justify-start box-border text-left text-base cursor-pointer leading-snug py-2 px-3 text-white bg-orange-400 hover:bg-orange-500',
  optionDisabled: 'flex items-center justify-start box-border text-left text-base leading-snug py-2 px-3 bg-gray-200',
  noOptions: 'py-2 px-3 text-gray-600 bg-white text-left rtl:text-right',
  noResults: 'py-2 px-3 text-gray-600 bg-white text-left rtl:text-right',
  spacer: 'h-9 py-px box-content',
  spinner: 'border-b-orange-400 animate-spin inline-block w-8 h-8 border-4 rounded-full',
}

export const baseStyle = {
  container: 'h-auto relative mx-auto w-full flex items-center justify-end box-border cursor-pointer border rounded text-base leading-snug outline-none',
  containerDisabled: 'h-auto relative mx-auto w-full flex items-center justify-end box-border border rounded text-base leading-snug outline-none',
  containerActive: 'h-auto relative mx-auto w-full flex items-center justify-end box-border cursor-pointer border rounded text-base leading-snug outline-none rounded-b-none',
  label: 'flex items-center h-full absolute left-0 top-0 pointer-events-none bg-transparent leading-snug pl-3.5',
  search: 'w-full absolute inset-0 outline-none appearance-none box-border border-0 text-base font-sans bg-white rounded pl-3.5',
  placeholder: 'flex items-center h-full absolute left-0 top-0 pointer-events-none bg-transparent leading-snug pl-3.5',
  clear: 'pr-3.5 relative z-10 opacity-40 transition duration-300 flex-shrink-0 flex-grow-0 flex hover:opacity-80',
  clearIcon: 'text-lg font-bold text-center pl-3',
  dropdown: 'absolute -left-px -right-px bottom-0 transform translate-y-full border -mt-px overflow-hidden overflow-y-auto z-50 flex flex-col rounded-b',
  dropdownHidden: 'hidden',
  options: 'flex flex-col list-none',
  option: 'flex items-center justify-start box-border text-left cursor-pointer text-base leading-snug',
  optionSelected: 'flex items-center justify-start box-border text-left cursor-pointer text-base leading-snug',
  optionDisabled: 'flex items-center justify-start box-border text-left text-base leading-snug',
  spacer: 'py-px box-content',
  spinner: 'animate-spin inline-block rounded-full',
}
